testdata/in/continue_in_catch.nen:3:3: invalid continue outside a loop
